# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0003_courses_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='skill_level',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
