# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0005_auto_20170227_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], max_length=50, null=True),
        ),
    ]
